export const SET_CONNECTED = 'SET_CONNECTED';

export const SET_PROVIDER = 'SET_PROVIDER';
export const REMOVE_PROVIDER = 'REMOVE_PROVIDER';

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';

export const SET_TOKEN_BALANCE = 'SET_TOKEN_BALANCE';
export const REMOVE_TOKEN_BALANCE = 'REMOVE_TOKEN_BALANCE';

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const REMOVE_TRANSACTIONS = 'REMOVE_TRANSACTIONS';

export const SET_CONTRACTS = 'SET_CONTRACTS';
export const REMOVE_CONTRACTS = 'REMOVE_CONTRACTS';
